name: Testes E2E agendados (Cypress)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
      timezone: 'America/Sao_Paulo'

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes Cypress
        run: npm test

      - name: Publicar screenshots (em caso de falha)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Publicar vídeos (em caso de falha)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
